receivers:
  otlp:
    protocols:
      grpc:  { endpoint: 0.0.0.0:4317 }
      http:  { endpoint: 0.0.0.0:4318 }

processors:
  batch: {}

exporters:
  # Send traces to Jaeger using OTLP gRPC
  otlp:
    endpoint: jaeger:4317
    tls:
      insecure: true
  # Optional: log what’s being exported
  logging:
    loglevel: info

service:
  pipelines:
    traces:
      receivers:  [otlp]
      processors: [batch]
      exporters:  [otlp, logging]
